# Generated by Django 3.2.9 on 2021-11-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterField(
            model_name='picture',
            name='parent_picture',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID Родительского изображения'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
