# Generated by Django 3.2.9 on 2022-10-18 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0003_auto_20221018_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='image_file',
            new_name='picture',
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='image_url',
            new_name='url',
        ),
        migrations.AlterField(
            model_name='picture',
            name='parent_picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='image_app.picture', verbose_name='Родительское изображение'),
        ),
    ]
