# Generated by Django 3.2.9 on 2024-02-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0005_alter_picture_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(upload_to='site_media/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
